#!/bin/bash

# O Git passa o caminho do arquivo que contém a mensagem como o primeiro argumento ($1)
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Regex para o padrão: [PETCONTROL-123] feat: descrição
# Explicação:
# ^\[PETCONTROL-[0-9]+\] -> Começa com [PETCONTROL- e números
# (feat|fix|chore|doc|refactor|test|style) -> Um dos tipos permitidos
# : .+ -> Dois pontos, espaço e uma descrição
PROJECT_KEY="PETCONTROL"

REGEX="^\[$PROJECT_KEY-[0-9]{3}\] (feat|fix|chore|doc|refactor|test|style): .+"

if [[ ! $COMMIT_MSG =~ $REGEX ]]; then
    echo "[ERROR] Invalid commit message format."
    echo "> Expected pattern: [$PROJECT_KEY-ID] type: description"
    echo "> Example: [$PROJECT_KEY-002] feat: add animal endpoint"
    echo "> Allowed types: feat, fix, chore, doc, refactor, test, style"
    exit 1
fi

exit 0
